import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Services from '../components/Service'
import Welcome from '../components/Welcome'
import Footer from '../components/Footer'
import { ethers } from 'ethers'
import Crowdfunding from "../artifacts/contracts/CrowdFunding.sol/crowdfunding.json"


export default function Home({ manager }) {


  return (
    <div >
      <Head>
        <title>CrowdFunding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="gradient-bg-welcome">
        <Navbar manager={manager} />
        <Welcome />

      </div>
      <Services />
      <Footer />


    </div>
  )
}


export async function getStaticProps() {

  const provider = new ethers.providers.JsonRpcProvider("https://eth-goerli.g.alchemy.com/v2/Qo1DxQ8U6Hzw3Da7p3n7zTlD0xUgMR4t");
  const contract = new ethers.Contract(process.env.CONTRACT_ADDRESS, Crowdfunding.abi, provider);

  const manager = await contract.manager();




  return {
    props: {
      manager

    }
  }
}